
export const HOME_ACTION_ON_SELECT_BOARD = 'HOME_ACTION_ON_SELECT_BOARD';
export const HOME_ACTION_ON_ADD_BOARD_BUTTON = 'HOME_ACTION_ON_ADD_BOARD_BUTTON';
export const HOME_ACTION_ON_CLOSE_BOARD_BUTTON = 'HOME_ACTION_ON_CLOSE_BOARD_BUTTON';
export const HOME_ACTION_ON_SELECT_TODO_BUTTON = 'HOME_ACTION_ON_SELECT_TODO_BUTTON';
export const HOME_ACTION_ON_ADD_TODO_BUTTON = 'HOME_ACTION_ON_ADD_TODO_BUTTON';
