
export const ADD_TODO_DIALOG_ACTION_ON_CLOSE = 'ADD_TODO_DIALOG_ACTION_ON_CLOSE';
export const ADD_TODO_DIALOG_ACTION_ON_SUBMIT = 'ADD_TODO_DIALOG_ACTION_ON_SUBMIT';
export const ADD_TODO_DIALOG_ACTION_ON_CHANGE = 'ADD_TODO_DIALOG_ACTION_ON_CHANGE';
