
export const ADD_BOARD_DIALOG_ACTION_ON_CLOSE = 'ADD_BOARD_DIALOG_ACTION_ON_CLOSE';
export const ADD_BOARD_DIALOG_ACTION_ON_SUBMIT = 'ADD_BOARD_DIALOG_ACTION_ON_SUBMIT';
export const ADD_BOARD_DIALOG_ACTION_ON_CHANGE = 'ADD_BOARD_DIALOG_ACTION_ON_CHANGE';
